### ISSUE TITLE
Steps to build my own docker-compose for NanoPI Neo2 Black

### ISSUE THREAD

**Issue by t-abraham** [AppTower/docker-compose#1]
Hello, I appreciate your effort to build the docker-compose for the ARMv7 Raspberry Pi 3. I am using NanoPI Neo2 Black. Could you please guide me step by step to build my own docker-compose for my device?

Thank you

**Comment by Ivan61** [comment]
You can follow this, https://github.com/docker/compose/issues/6831#issuecomment-568815378.
This is a containerized docker-compose container. You can run it directly even if you are not playing raspbian. Btw, multiple architectures of linux/arm64 and linux/arm are supported from version 1.25.4.
https://hub.docker.com/r/apptower/docker-compose/tags
