### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by leech001** [AppTower/docker-compose#2]
Hi. Are you planning to update the version?

**Comment by Ivan61** [comment]
Hi, I have just finished it.

**apptower/docker-compose:1.26.0**
|DIGEST|OS/ARCH|COMPRESSED SIZE|REMARK|
| :-------------: | :-------------: | :-------------: | :-------------: |
|8826290a3d46|linux/amd64|29.24 MB|reference to docker/compose:1.26.0|
|39ba07327903|linux/arm/v6|25.95 MB||
|f48fbfeb34a9|linux/arm/v7|25.15 MB||
|24754209bf4f|linux/arm64|26.01 MB||
